#cloud-config
datasource:
  GCE:
    sec_between_retries: 5

runcmd:
  - [ bash, -lc, "mkdir -p /etc/motd.d && ln -sf /dev/null /etc/motd.d/50-default" ]

# Enable `linger` so the `ubuntu` user's `systemd` runs on boot (with no login)
# This is required for snap user daemons and timers to run reliably on UC
#  - [ loginctl, enable-linger, ubuntu ]

# Ensure that `snapd`’s per-user session agent socket is actually active for the `ubuntu` user
# `snapd` uses this to manage user-scoped services; without it installing and/or enabling snaps with `daemon-scope: user` set can fail
#  - [ bash, -lc, 'UID=$(id -u ubuntu); systemctl start user@$UID.service; sudo -u ubuntu env XDG_RUNTIME_DIR=/run/user/$UID DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus systemctl --user enable --now snapd.session-agent.socket' ]

write_files:
  - path: /etc/motd.d/99-custom-google-cloud
    owner: root:root
    permissions: "0644"
    defer: true
    content: |
      Welcome to Ubuntu Core 26

      * Documentation: https://ubuntu.com/core/docs

      This is a pre-built Ubuntu Core image. Pre-built images are ideal for
      exploration as you develop your own custom Ubuntu Core image.

      To learn how to create your custom Ubuntu Core image, see our guide:

      * Getting Started: https://ubuntu.com/core/docs/get-started

      * First steps: https://ubuntu.com/core/docs/first-steps